version: 2 # use CircleCI 2.0
general:
  branches:
    only:
      - Test 
    ignore:
      - Master
      
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    
    working_directory: ~/JenkinsWar # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-browsers # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: JenkinsWar-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline # gets the project dependencies
      
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: JenkinsWar-{{ checksum "pom.xml" }}
      
      - run: mvn package # run the actual tests
      
      #- store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard. 
      #    path: target/surefire-reports
      
      - store_artifacts: # store the uberjar as an artifact
          path: target/JenkinsWar.war
 
      #- add_ssh_keys:
      #    fingerprints:
      #    - "2e:aa:e2:7d:41:35:f2:34:66:58:d8:56:7b:91:c1:b2"
